version: '3.7'
services:
  mongodb-Cont:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_cont:/data/db
volumes:
  mongodb_data_cont:
